### PR TITLE
CA-186157: xsiostat: Add xen-libs-devel build dependency

### PR DESCRIPTION
**Pull request by rafalmiel**
It is required to access xenstore by xsiostat

### CODE REVIEW

**Comment by xen-git** [comment]
Can one of the admins verify this patch for testing?

**Comment by johnelse** [comment]
@xen-git test this please

**Comment by johnelse** [comment]
Looks fine!

**Comment by johnelse** [comment]
Actually, I'm going to merge this now - it doesn't need to wait for the low_mem_mode flag like the other two PRs.

**Pull request merged**
